Adding docs
quarkiverse/quarkus-embedded-postgresql pull request #16
Opened 2023-02-20 18:15 UTC by fjtirado

2023-02-20 18:19 UTC, gastaldi commented on docs/pom.xml
> +                        <phase>prepare-package</phase>
```suggestion
                        <phase>generate-resources</phase>
```

2023-02-20 20:02 UTC, gastaldi requested changes
Don't add/change .github/project.yml here because it will trigger a release.

2023-02-21 00:17 UTC, fjtirado commented
@gastaldi Sure, It was unclear to me, changed

2023-02-21 00:21 UTC, gastaldi approved these changes

2023-02-21 00:37 UTC, merged